const categorySentences: Record<string, string> = {
  Baseball: "Let's go play baseball",
  Basketball: "Let's go play basketball",
  Boating: "Let's go boating",
  Camping: "Let's go camping",
  'Car Shows': "Let's go to car shows",
  Cardio: "Let's go do cardio",
  Concerts: "Let's go to concerts",
  Crocheting: "Let's go crochet",
  Culture: "Let's go talk culture",
  'Desserts & Pastry': "Let's go bake desserts and pastries",
  Drawing: "Let's go draw",
  Fishing: "Let's go fish",
  Hardware: "Let's go build hardware",
  Hiking: "Let's go hiking",
  History: "Let's go talk history",
  'International Cuisine': "Let's go cook international cuisine",
  Knitting: "Let's go knit",
  Lifting: "Let's go lift",
  Math: "Let's go study math",
  'Meal Prep': "Let's go meal prep",
  Meditation: "Let's go meditate",
  Motorbikes: "Let's go motorbike",
  Nutrition: "Let's go talk nutrition",
  Painting: "Let's go paint",
  Philosophy: "Let's go talk philosophy",
  Pilates: "Let's go do pilates",
  'Playing Instruments': "Let's go play instruments",
  Poetry: "Let's go write poetry",
  Pottery: "Let's go make pottery",
  Racing: "Let's go race",
  Reading: "Let's go read",
  Rollerskating: "Let's go roller skating",
  Science: "Let's go study science",
  Sculpting: "Let's go sculpt",
  'Self-Improvement': "Let's go talk self improvement",
  Sewing: "Let's go sew",
  Skating: "Let's go skating",
  Skiing: "Let's go skiing",
  Snowboarding: "Let's go snowboarding",
  Software: "Let's go build software",
  Studying: "Let's go study",
  Trains: "Let's go talk trains",
  Tutoring: "Let's go tutor",
  Vegan: "Let's go cook vegan food",
  Vegetarian: "Let's go cook vegetarian food",
  Volleyball: "Let's go play volleyball",
  Yoga: "Let's go do yoga",
};

export default categorySentences;
